### PR TITLE
Add KudasaiJP as bartio validator

### PR DESCRIPTION
**Pull request by liray-unendlich**
#129 
Please add KudasaiJP as default validator!

### CODE REVIEW

**Comment by meithebear** [comment]
Please resolve merge conflicts.

**Comment by liray-unendlich** [comment]
@meithebear Thanks for check! just updated

**Comment by meithebear** [comment]
Please resolve merge conflicts and tag me, will merge for you once resolved! Ty

**Comment by liray-unendlich** [comment]
@meithebear how about now?

**Review by meithebear — APPROVED** [review]

**Pull request merged**
