### PR TITLE
Add Simply Staking

### LINKED ISSUE #142: Add Simply Staking
- [x] I understand that filing an issue does not guarantee addition to the Berachain default validator list.
- [x] I will not ping the Discord about this listing request.

**Please follow the format for your validator.**

```json
{
    "id": "0x23A3f18cFEF4625E3fBe5850E7Ac33E8F0f6E20c",
    "logoURI": "https://res.cloudinary.com/duv0g402y/raw/upload/src/assets/simplystaking.png",
    "name": "Simply Staking",
    "description": "Simply Staking runs highly reliable infrastructure in our own datacentre in Malta, built with the aim of supporting the growth of the blockchain ecosystem",
    "website": "https://simplystaking.com",
    "twitter": "https://x.com/SimplyStaking"
},
```

- id: validator fee recipient
- logoURI: path to validator icon in default-list repo
- name: validator name
- description (optional): a short description for the validator
- website (optional): a validator's website
- twitter (optiona): a validator's twitter account url

this repository is uploaded to cloudinary for improved availability. Please upload your relevant assets under the `assets/` folder and prefix the path in this json file with `https://res.cloudinary.com/duv0g402y/raw/upload/`.

an example :
`https://res.cloudinary.com/duv0g402y/raw/upload/src/assets/${asset_file_name}`
ℹ️ AFTER OPENING AN ISSUE, CREATE A BRANCH AND ADD YOUR CHANGES. WHEN READY, CREATE A PR AND LINK YOUR ISSUE IN THE PR 🚀

### PR DESCRIPTION
**Pull request by Cabbache**
Fixes #142

### CODE REVIEW

**Comment by meithebear** [comment]
Please check if your logo is uploaded correctly by click onto the cloudinary logo url after merging

**Comment by meithebear** [comment]
Please resolve merge conflicts

**Comment by meithebear** [comment]
Please fix linting issue

**Comment by Cabbache** [comment]
All issues resolved

**Review by meithebear — APPROVED** [review]

**Pull request merged**
