### PR TITLE
Add 1XP

### PR DESCRIPTION
**Pull request by jjangg96**
Add 1XP #69

### CODE REVIEW

**Comment by meithebear** [comment]
Please resolve merge conflicts

**Comment by jjangg96** [comment]
Updated.

**Comment by jjangg96** [comment]
Updated again.

**Review by corduroybera — APPROVED** [review]

**Comment by jjangg96** [comment]
It conflicted again, so I moved it to the top to avoid the conflict.

**Comment by jjangg96** [comment]
> Please resolve merge conflicts

It conflicted again, so I moved it to the top to avoid the conflict.

**Pull request merged**
